apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutating-webhook
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      containers:
      - name: mutating-webhook
        image: ${YOUR MUTATING WEBHOOK IMAGE}
        ports:
        - containerPort: 5000
        env: # The original example from https://github.com/k-mitevski/kubernetes-mutating-webhook, which lets webhook read the value of NODE_POOL
        - name: NODE_POOL
          value: "kubernetes.io/hostname: docker-desktop"
        volumeMounts:
        - name: certs-volume
          readOnly: true
          mountPath: "/certs"
      volumes:
      - name: certs-volume
        secret:
          secretName: admission-tls
